import { describe, it, expect } from 'vitest';
import { readFileSync } from 'node:fs';
import type { ItemState, PatchData, PlacedMod } from './index.ts';
import { loadPatch, addAffixProbability } from './index.ts';

// Full-branch differential: `addAffixProbability` (the shared transmute/aug/regal/exalt math) vs the
// Java `NormalCompute`, across item states that hit every branch — both-slots-open, prefix-only
// (3 suffixes), suffix-only (3 prefixes), and family exclusion. Fixtures generated by
// `core.data.AddAffixProbe` from packages/engine/src/__fixtures__/scenarios.json.

interface Scenario { name: string; base: string; placed: string[]; }
interface ScenariosFile { patch: string; scenarios: Scenario[]; }
interface Variants { base: number; greater: number; perfect: number; sinistral?: number; dextral?: number; }
interface Fixture { patch: string; scenarios: Record<string, Record<string, Variants>>; }

const DIR = 'packages/engine/src/__fixtures__';
const scenariosFile = JSON.parse(readFileSync(`${DIR}/scenarios.json`, 'utf8')) as ScenariosFile;
const fixture = JSON.parse(readFileSync(`${DIR}/addaffix-java.json`, 'utf8')) as Fixture;
const data = loadPatch('data/patches/0.5');

function buildItem(scenario: Scenario): ItemState {
  const base = data.bases.get(scenario.base);
  if (!base) throw new Error(`no base ${scenario.base}`);
  const prefixes: PlacedMod[] = [];
  const suffixes: PlacedMod[] = [];
  for (const id of scenario.placed) {
    const m = data.mods.get(id);
    if (!m) throw new Error(`no mod ${id}`);
    const placed: PlacedMod = { modId: id, tierName: m.tiers[0]!.name };
    if (m.type === 'prefix') prefixes.push(placed); else suffixes.push(placed);
  }
  return { base, level: 100, rarity: 'rare', prefixes, suffixes };
}

describe('add-affix — TS vs Java differential across all NormalCompute branches', () => {
  expect(data.patch).toBe(fixture.patch);

  for (const scenario of scenariosFile.scenarios) {
    const probs = fixture.scenarios[scenario.name];
    describe(scenario.name, () => {
      it('scenario present in fixture', () => expect(probs).toBeDefined());
      const item = buildItem(scenario);

      for (const [modId, v] of Object.entries(probs ?? {})) {
        it(`${modId}: base/greater/perfect/omen match Java`, () => {
          // base floor (0), greater (35), perfect (50) currency strengths
          expect(addAffixProbability(data, item, modId, { floor: 0 })).toBeCloseTo(v.base, 12);
          expect(addAffixProbability(data, item, modId, { floor: 35 })).toBeCloseTo(v.greater, 12);
          expect(addAffixProbability(data, item, modId, { floor: 50 })).toBeCloseTo(v.perfect, 12);
          // omen side-constraint (Sinistral = prefix-only, Dextral = suffix-only)
          if (v.sinistral !== undefined) {
            expect(addAffixProbability(data, item, modId, { floor: 0, constrainTo: 'prefix' })).toBeCloseTo(v.sinistral, 12);
          }
          if (v.dextral !== undefined) {
            expect(addAffixProbability(data, item, modId, { floor: 0, constrainTo: 'suffix' })).toBeCloseTo(v.dextral, 12);
          }
        });
      }
    });
  }
});
