import { describe, it, expect } from 'vitest';
import { readFileSync } from 'node:fs';
import { loadPatch, transmuteProbability } from './index.ts';

// Differential test: the TS transmute probability must match the Java engine's exactly, on the same
// patch data. Fixture is generated by `core.data.TransmuteProbe` (see tools/refresh/README or
// package.json script `fixtures:java`). Regenerate it whenever the transmute math or 0.5 data changes.
//
// CLAUDE.md: "every TS engine mechanic must match the Java engine's output on the same input before
// the Java version is retired. Divergence = investigate, don't average."

interface Fixture { patch: string; bases: Record<string, Record<string, number>>; }

const FIXTURE = 'packages/engine/src/__fixtures__/transmute-java.json';
const PATCH_DIR = 'data/patches/0.5';

describe('transmute — TS vs Java differential (patch 0.5)', () => {
  const fixture = JSON.parse(readFileSync(FIXTURE, 'utf8')) as Fixture;
  const data = loadPatch(PATCH_DIR);
  expect(data.patch).toBe(fixture.patch);

  for (const [baseId, probs] of Object.entries(fixture.bases)) {
    describe(baseId, () => {
      const base = data.bases.get(baseId);
      it('base exists', () => { expect(base).toBeDefined(); });

      for (const [modId, javaP] of Object.entries(probs)) {
        it(`${modId} matches Java (${javaP.toFixed(6)})`, () => {
          expect(transmuteProbability(data, base!, modId)).toBeCloseTo(javaP, 12);
        });
      }

      it('TS distribution over the pool also sums to 1', () => {
        const total = Object.keys(probs).reduce((s, id) => s + transmuteProbability(data, base!, id), 0);
        expect(total).toBeCloseTo(1, 9);
      });
    });
  }
});
