name: Data Issue
description: Report incorrect modifier data, probabilities, or game mechanics
title: "[Data]: "
labels: ["data", "bug"]
body:
  - type: markdown
    attributes:
      value: |
        Report issues with item modifiers, weights, or crafting mechanics data.
        
  - type: dropdown
    id: data-type
    attributes:
      label: What type of data issue is this?
      options:
        - Incorrect modifier weights
        - Missing modifier
        - Wrong item level requirements
        - Incorrect tags
        - Wrong probability calculation
        - Outdated game mechanics
        - Other
    validations:
      required: true
      
  - type: textarea
    id: description
    attributes:
      label: Describe the data issue
      description: What data is incorrect or missing?
      placeholder: The modifier "X" on "Y" item has incorrect weight...
    validations:
      required: true
      
  - type: textarea
    id: current-data
    attributes:
      label: Current data in the tool
      description: What does the tool currently show?
      placeholder: |
        Modifier: "Increased Fire Damage"
        Weight: 1000
        Item Level: 10
      
  - type: textarea
    id: correct-data
    attributes:
      label: Correct data
      description: What should it be? Include sources if possible
      placeholder: |
        According to [source], it should be:
        Weight: 500
        Item Level: 15
    validations:
      required: true
      
  - type: input
    id: item
    attributes:
      label: Affected item(s)
      description: Which item type is affected?
      placeholder: e.g., "Archon Plate", "Jade Ring", "All helmets"
      
  - type: input
    id: game-version
    attributes:
      label: Game version
      description: Which patch version is this based on?
      placeholder: e.g., "0.1.0e"
      
  - type: textarea
    id: source
    attributes:
      label: Source or evidence
      description: Links to wiki, datamined info, or screenshots
      placeholder: |
        - poedb.tw link
        - In-game screenshot
        - Community testing results
      
  - type: textarea
    id: additional
    attributes:
      label: Additional context
      description: Any other relevant information
