/**
 * Error codes returned from backend or generated by frontend
 */
export enum ErrorCode {
  BACKEND_UNAVAILABLE = 'BACKEND_UNAVAILABLE',
  INVALID_ITEM_ID = 'INVALID_ITEM_ID',
  INVALID_MODIFIERS = 'INVALID_MODIFIERS',
  INCOMPATIBLE_MODIFIERS = 'INCOMPATIBLE_MODIFIERS',
  FAMILY_CONFLICT = 'family_conflict',
  NO_VALID_PATH = 'NO_VALID_PATH',
  TIMEOUT = 'TIMEOUT',
  UNKNOWN = 'UNKNOWN',
}

/**
 * User-friendly error messages mapped from error codes
 * Used for FR-015 (graceful error handling)
 */
export const errorMessages: Record<ErrorCode, string> = {
  [ErrorCode.BACKEND_UNAVAILABLE]:
    'Cannot connect to crafting engine. Please restart the application.',
  [ErrorCode.INVALID_ITEM_ID]:
    'Selected item is invalid. Please select a different item.',
  [ErrorCode.INVALID_MODIFIERS]:
    'Selected modifiers are invalid. Try different combinations.',
  [ErrorCode.INCOMPATIBLE_MODIFIERS]:
    'Selected modifiers cannot coexist. Please adjust your selection.',
  [ErrorCode.FAMILY_CONFLICT]:
    'Modifier family conflict detected. See details above.',
  [ErrorCode.NO_VALID_PATH]:
    'No crafting path exists for these modifiers. Try removing one and retrying.',
  [ErrorCode.TIMEOUT]:
    'Simulation taking longer than expected. The combination may be extremely complex.',
  [ErrorCode.UNKNOWN]:
    'An unexpected error occurred. Please try again.',
};

/**
 * Get user-friendly error message from error code
 * @param code - Error code from backend or generated by frontend
 * @returns User-friendly error message
 */
export function getErrorMessage(code: ErrorCode | string): string {
  if (code in errorMessages) {
    return errorMessages[code as ErrorCode];
  }
  return errorMessages[ErrorCode.UNKNOWN];
}
