// Generated by generate_item_lookup_api.py
// This function maps item_id + source + type to the correct ModifierLookup table

#include <stddef.h>
#include <stdbool.h>
#include "modifiers.h"
#include "item_mod_lookup.h"

static ModifierLookup* get_lookup_table(int item_id, ModifierSource source, bool is_suffix, int* out_count) {
    if (!out_count) return NULL;
    *out_count = 0;
    
    ModifierLookup* table = NULL;
    int count = 0;
    
    switch (item_id) {
        case 4: // amulets
            switch (source) {
                case SOURCE_NORMAL:
                    if (!is_suffix) {
                        extern ModifierLookup amulets_normal_prefixes[];
                        table = amulets_normal_prefixes;
                        count = 10;
                    }
                    else {
                        extern ModifierLookup amulets_normal_suffixes[];
                        table = amulets_normal_suffixes;
                        count = 21;
                    }
                    break;
                case SOURCE_DESECRATED:
                    if (!is_suffix) {
                        extern ModifierLookup amulets_desecrated_prefixes[];
                        table = amulets_desecrated_prefixes;
                        count = 11;
                    }
                    else {
                        extern ModifierLookup amulets_desecrated_suffixes[];
                        table = amulets_desecrated_suffixes;
                        count = 19;
                    }
                    break;
                case SOURCE_ESSENCE:
                    if (!is_suffix) {
                        extern ModifierLookup amulets_essence_prefixes[];
                        table = amulets_essence_prefixes;
                        count = 3;
                    }
                    else {
                        extern ModifierLookup amulets_essence_suffixes[];
                        table = amulets_essence_suffixes;
                        count = 12;
                    }
                    break;
                default:
                    break;
            }
            break;
        case 35: // body_armours_dex
            switch (source) {
                case SOURCE_NORMAL:
                    if (!is_suffix) {
                        extern ModifierLookup body_armours_dex_normal_prefixes[];
                        table = body_armours_dex_normal_prefixes;
                        count = 7;
                    }
                    else {
                        extern ModifierLookup body_armours_dex_normal_suffixes[];
                        table = body_armours_dex_normal_suffixes;
                        count = 12;
                    }
                    break;
                case SOURCE_DESECRATED:
                    if (is_suffix) {
                        extern ModifierLookup body_armours_dex_desecrated_suffixes[];
                        table = body_armours_dex_desecrated_suffixes;
                        count = 12;
                    }
                    break;
                case SOURCE_ESSENCE:
                    if (!is_suffix) {
                        extern ModifierLookup body_armours_dex_essence_prefixes[];
                        table = body_armours_dex_essence_prefixes;
                        count = 5;
                    }
                    else {
                        extern ModifierLookup body_armours_dex_essence_suffixes[];
                        table = body_armours_dex_essence_suffixes;
                        count = 6;
                    }
                    break;
                default:
                    break;
            }
            break;
        case 36: // body_armours_dex_int
            switch (source) {
                case SOURCE_NORMAL:
                    if (!is_suffix) {
                        extern ModifierLookup body_armours_dex_int_normal_prefixes[];
                        table = body_armours_dex_int_normal_prefixes;
                        count = 7;
                    }
                    else {
                        extern ModifierLookup body_armours_dex_int_normal_suffixes[];
                        table = body_armours_dex_int_normal_suffixes;
                        count = 14;
                    }
                    break;
                case SOURCE_DESECRATED:
                    if (is_suffix) {
                        extern ModifierLookup body_armours_dex_int_desecrated_suffixes[];
                        table = body_armours_dex_int_desecrated_suffixes;
                        count = 13;
                    }
                    break;
                case SOURCE_ESSENCE:
                    if (!is_suffix) {
                        extern ModifierLookup body_armours_dex_int_essence_prefixes[];
                        table = body_armours_dex_int_essence_prefixes;
                        count = 5;
                    }
                    else {
                        extern ModifierLookup body_armours_dex_int_essence_suffixes[];
                        table = body_armours_dex_int_essence_suffixes;
                        count = 7;
                    }
                    break;
                default:
                    break;
            }
            break;
        case 34: // body_armours_int
            switch (source) {
                case SOURCE_NORMAL:
                    if (!is_suffix) {
                        extern ModifierLookup body_armours_int_normal_prefixes[];
                        table = body_armours_int_normal_prefixes;
                        count = 7;
                    }
                    else {
                        extern ModifierLookup body_armours_int_normal_suffixes[];
                        table = body_armours_int_normal_suffixes;
                        count = 12;
                    }
                    break;
                case SOURCE_DESECRATED:
                    if (is_suffix) {
                        extern ModifierLookup body_armours_int_desecrated_suffixes[];
                        table = body_armours_int_desecrated_suffixes;
                        count = 11;
                    }
                    break;
                case SOURCE_ESSENCE:
                    if (!is_suffix) {
                        extern ModifierLookup body_armours_int_essence_prefixes[];
                        table = body_armours_int_essence_prefixes;
                        count = 5;
                    }
                    else {
                        extern ModifierLookup body_armours_int_essence_suffixes[];
                        table = body_armours_int_essence_suffixes;
                        count = 6;
                    }
                    break;
                default:
                    break;
            }
            break;
        case 31: // body_armours_str
            switch (source) {
                case SOURCE_NORMAL:
                    if (!is_suffix) {
                        extern ModifierLookup body_armours_str_normal_prefixes[];
                        table = body_armours_str_normal_prefixes;
                        count = 7;
                    }
                    else {
                        extern ModifierLookup body_armours_str_normal_suffixes[];
                        table = body_armours_str_normal_suffixes;
                        count = 12;
                    }
                    break;
                case SOURCE_DESECRATED:
                    if (is_suffix) {
                        extern ModifierLookup body_armours_str_desecrated_suffixes[];
                        table = body_armours_str_desecrated_suffixes;
                        count = 10;
                    }
                    break;
                case SOURCE_ESSENCE:
                    if (!is_suffix) {
                        extern ModifierLookup body_armours_str_essence_prefixes[];
                        table = body_armours_str_essence_prefixes;
                        count = 5;
                    }
                    else {
                        extern ModifierLookup body_armours_str_essence_suffixes[];
                        table = body_armours_str_essence_suffixes;
                        count = 6;
                    }
                    break;
                default:
                    break;
            }
            break;
        case 32: // body_armours_str_int
            switch (source) {
                case SOURCE_NORMAL:
                    if (!is_suffix) {
                        extern ModifierLookup body_armours_str_int_normal_prefixes[];
                        table = body_armours_str_int_normal_prefixes;
                        count = 7;
                    }
                    else {
                        extern ModifierLookup body_armours_str_int_normal_suffixes[];
                        table = body_armours_str_int_normal_suffixes;
                        count = 14;
                    }
                    break;
                case SOURCE_DESECRATED:
                    if (is_suffix) {
                        extern ModifierLookup body_armours_str_int_desecrated_suffixes[];
                        table = body_armours_str_int_desecrated_suffixes;
                        count = 11;
                    }
                    break;
                case SOURCE_ESSENCE:
                    if (!is_suffix) {
                        extern ModifierLookup body_armours_str_int_essence_prefixes[];
                        table = body_armours_str_int_essence_prefixes;
                        count = 5;
                    }
                    else {
                        extern ModifierLookup body_armours_str_int_essence_suffixes[];
                        table = body_armours_str_int_essence_suffixes;
                        count = 7;
                    }
                    break;
                default:
                    break;
            }
            break;
        case 33: // body_armours_str_dex
            switch (source) {
                case SOURCE_NORMAL:
                    if (!is_suffix) {
                        extern ModifierLookup body_armours_str_dex_normal_prefixes[];
                        table = body_armours_str_dex_normal_prefixes;
                        count = 7;
                    }
                    else {
                        extern ModifierLookup body_armours_str_dex_normal_suffixes[];
                        table = body_armours_str_dex_normal_suffixes;
                        count = 14;
                    }
                    break;
                case SOURCE_DESECRATED:
                    if (is_suffix) {
                        extern ModifierLookup body_armours_str_dex_desecrated_suffixes[];
                        table = body_armours_str_dex_desecrated_suffixes;
                        count = 12;
                    }
                    break;
                case SOURCE_ESSENCE:
                    if (!is_suffix) {
                        extern ModifierLookup body_armours_str_dex_essence_prefixes[];
                        table = body_armours_str_dex_essence_prefixes;
                        count = 5;
                    }
                    else {
                        extern ModifierLookup body_armours_str_dex_essence_suffixes[];
                        table = body_armours_str_dex_essence_suffixes;
                        count = 7;
                    }
                    break;
                default:
                    break;
            }
            break;
        case 20: // boots_dex
            switch (source) {
                case SOURCE_NORMAL:
                    if (!is_suffix) {
                        extern ModifierLookup boots_dex_normal_prefixes[];
                        table = boots_dex_normal_prefixes;
                        count = 6;
                    }
                    else {
                        extern ModifierLookup boots_dex_normal_suffixes[];
                        table = boots_dex_normal_suffixes;
                        count = 13;
                    }
                    break;
                case SOURCE_DESECRATED:
                    if (is_suffix) {
                        extern ModifierLookup boots_dex_desecrated_suffixes[];
                        table = boots_dex_desecrated_suffixes;
                        count = 15;
                    }
                    break;
                case SOURCE_ESSENCE:
                    if (!is_suffix) {
                        extern ModifierLookup boots_dex_essence_prefixes[];
                        table = boots_dex_essence_prefixes;
                        count = 4;
                    }
                    else {
                        extern ModifierLookup boots_dex_essence_suffixes[];
                        table = boots_dex_essence_suffixes;
                        count = 7;
                    }
                    break;
                default:
                    break;
            }
            break;
        case 21: // boots_dex_int
            switch (source) {
                case SOURCE_NORMAL:
                    if (!is_suffix) {
                        extern ModifierLookup boots_dex_int_normal_prefixes[];
                        table = boots_dex_int_normal_prefixes;
                        count = 6;
                    }
                    else {
                        extern ModifierLookup boots_dex_int_normal_suffixes[];
                        table = boots_dex_int_normal_suffixes;
                        count = 15;
                    }
                    break;
                case SOURCE_DESECRATED:
                    if (is_suffix) {
                        extern ModifierLookup boots_dex_int_desecrated_suffixes[];
                        table = boots_dex_int_desecrated_suffixes;
                        count = 15;
                    }
                    break;
                case SOURCE_ESSENCE:
                    if (!is_suffix) {
                        extern ModifierLookup boots_dex_int_essence_prefixes[];
                        table = boots_dex_int_essence_prefixes;
                        count = 4;
                    }
                    else {
                        extern ModifierLookup boots_dex_int_essence_suffixes[];
                        table = boots_dex_int_essence_suffixes;
                        count = 8;
                    }
                    break;
                default:
                    break;
            }
            break;
        case 19: // boots_int
            switch (source) {
                case SOURCE_NORMAL:
                    if (!is_suffix) {
                        extern ModifierLookup boots_int_normal_prefixes[];
                        table = boots_int_normal_prefixes;
                        count = 6;
                    }
                    else {
                        extern ModifierLookup boots_int_normal_suffixes[];
                        table = boots_int_normal_suffixes;
                        count = 13;
                    }
                    break;
                case SOURCE_DESECRATED:
                    if (is_suffix) {
                        extern ModifierLookup boots_int_desecrated_suffixes[];
                        table = boots_int_desecrated_suffixes;
                        count = 15;
                    }
                    break;
                case SOURCE_ESSENCE:
                    if (!is_suffix) {
                        extern ModifierLookup boots_int_essence_prefixes[];
                        table = boots_int_essence_prefixes;
                        count = 4;
                    }
                    else {
                        extern ModifierLookup boots_int_essence_suffixes[];
                        table = boots_int_essence_suffixes;
                        count = 7;
                    }
                    break;
                default:
                    break;
            }
            break;
        case 18: // boots_str
            switch (source) {
                case SOURCE_NORMAL:
                    if (!is_suffix) {
                        extern ModifierLookup boots_str_normal_prefixes[];
                        table = boots_str_normal_prefixes;
                        count = 6;
                    }
                    else {
                        extern ModifierLookup boots_str_normal_suffixes[];
                        table = boots_str_normal_suffixes;
                        count = 13;
                    }
                    break;
                case SOURCE_DESECRATED:
                    if (is_suffix) {
                        extern ModifierLookup boots_str_desecrated_suffixes[];
                        table = boots_str_desecrated_suffixes;
                        count = 15;
                    }
                    break;
                case SOURCE_ESSENCE:
                    if (!is_suffix) {
                        extern ModifierLookup boots_str_essence_prefixes[];
                        table = boots_str_essence_prefixes;
                        count = 4;
                    }
                    else {
                        extern ModifierLookup boots_str_essence_suffixes[];
                        table = boots_str_essence_suffixes;
                        count = 7;
                    }
                    break;
                default:
                    break;
            }
            break;
        case 22: // boots_str_dex
            switch (source) {
                case SOURCE_NORMAL:
                    if (!is_suffix) {
                        extern ModifierLookup boots_str_dex_normal_prefixes[];
                        table = boots_str_dex_normal_prefixes;
                        count = 6;
                    }
                    else {
                        extern ModifierLookup boots_str_dex_normal_suffixes[];
                        table = boots_str_dex_normal_suffixes;
                        count = 15;
                    }
                    break;
                case SOURCE_DESECRATED:
                    if (is_suffix) {
                        extern ModifierLookup boots_str_dex_desecrated_suffixes[];
                        table = boots_str_dex_desecrated_suffixes;
                        count = 15;
                    }
                    break;
                case SOURCE_ESSENCE:
                    if (!is_suffix) {
                        extern ModifierLookup boots_str_dex_essence_prefixes[];
                        table = boots_str_dex_essence_prefixes;
                        count = 4;
                    }
                    else {
                        extern ModifierLookup boots_str_dex_essence_suffixes[];
                        table = boots_str_dex_essence_suffixes;
                        count = 8;
                    }
                    break;
                default:
                    break;
            }
            break;
        case 17: // boots_str_int
            switch (source) {
                case SOURCE_NORMAL:
                    if (!is_suffix) {
                        extern ModifierLookup boots_str_int_normal_prefixes[];
                        table = boots_str_int_normal_prefixes;
                        count = 6;
                    }
                    else {
                        extern ModifierLookup boots_str_int_normal_suffixes[];
                        table = boots_str_int_normal_suffixes;
                        count = 15;
                    }
                    break;
                case SOURCE_DESECRATED:
                    if (is_suffix) {
                        extern ModifierLookup boots_str_int_desecrated_suffixes[];
                        table = boots_str_int_desecrated_suffixes;
                        count = 15;
                    }
                    break;
                case SOURCE_ESSENCE:
                    if (!is_suffix) {
                        extern ModifierLookup boots_str_int_essence_prefixes[];
                        table = boots_str_int_essence_prefixes;
                        count = 4;
                    }
                    else {
                        extern ModifierLookup boots_str_int_essence_suffixes[];
                        table = boots_str_int_essence_suffixes;
                        count = 8;
                    }
                    break;
                default:
                    break;
            }
            break;
        case 0: // bows
            switch (source) {
                case SOURCE_NORMAL:
                    if (!is_suffix) {
                        extern ModifierLookup bows_normal_prefixes[];
                        table = bows_normal_prefixes;
                        count = 8;
                    }
                    else {
                        extern ModifierLookup bows_normal_suffixes[];
                        table = bows_normal_suffixes;
                        count = 13;
                    }
                    break;
                case SOURCE_DESECRATED:
                    if (!is_suffix) {
                        extern ModifierLookup bows_desecrated_prefixes[];
                        table = bows_desecrated_prefixes;
                        count = 7;
                    }
                    else {
                        extern ModifierLookup bows_desecrated_suffixes[];
                        table = bows_desecrated_suffixes;
                        count = 8;
                    }
                    break;
                case SOURCE_ESSENCE:
                    if (!is_suffix) {
                        extern ModifierLookup bows_essence_prefixes[];
                        table = bows_essence_prefixes;
                        count = 9;
                    }
                    else {
                        extern ModifierLookup bows_essence_suffixes[];
                        table = bows_essence_suffixes;
                        count = 7;
                    }
                    break;
                default:
                    break;
            }
            break;
        case 23: // bucklers
            switch (source) {
                case SOURCE_NORMAL:
                    if (!is_suffix) {
                        extern ModifierLookup bucklers_normal_prefixes[];
                        table = bucklers_normal_prefixes;
                        count = 6;
                    }
                    else {
                        extern ModifierLookup bucklers_normal_suffixes[];
                        table = bucklers_normal_suffixes;
                        count = 13;
                    }
                    break;
                case SOURCE_DESECRATED:
                    if (is_suffix) {
                        extern ModifierLookup bucklers_desecrated_suffixes[];
                        table = bucklers_desecrated_suffixes;
                        count = 12;
                    }
                    break;
                case SOURCE_ESSENCE:
                    if (!is_suffix) {
                        extern ModifierLookup bucklers_essence_prefixes[];
                        table = bucklers_essence_prefixes;
                        count = 5;
                    }
                    else {
                        extern ModifierLookup bucklers_essence_suffixes[];
                        table = bucklers_essence_suffixes;
                        count = 7;
                    }
                    break;
                default:
                    break;
            }
            break;
        case 1: // crossbows
            switch (source) {
                case SOURCE_NORMAL:
                    if (!is_suffix) {
                        extern ModifierLookup crossbows_normal_prefixes[];
                        table = crossbows_normal_prefixes;
                        count = 8;
                    }
                    else {
                        extern ModifierLookup crossbows_normal_suffixes[];
                        table = crossbows_normal_suffixes;
                        count = 14;
                    }
                    break;
                case SOURCE_DESECRATED:
                    if (!is_suffix) {
                        extern ModifierLookup crossbows_desecrated_prefixes[];
                        table = crossbows_desecrated_prefixes;
                        count = 6;
                    }
                    else {
                        extern ModifierLookup crossbows_desecrated_suffixes[];
                        table = crossbows_desecrated_suffixes;
                        count = 7;
                    }
                    break;
                case SOURCE_ESSENCE:
                    if (!is_suffix) {
                        extern ModifierLookup crossbows_essence_prefixes[];
                        table = crossbows_essence_prefixes;
                        count = 9;
                    }
                    else {
                        extern ModifierLookup crossbows_essence_suffixes[];
                        table = crossbows_essence_suffixes;
                        count = 7;
                    }
                    break;
                default:
                    break;
            }
            break;
        case 39: // foci
            switch (source) {
                case SOURCE_NORMAL:
                    if (!is_suffix) {
                        extern ModifierLookup foci_normal_prefixes[];
                        table = foci_normal_prefixes;
                        count = 11;
                    }
                    else {
                        extern ModifierLookup foci_normal_suffixes[];
                        table = foci_normal_suffixes;
                        count = 13;
                    }
                    break;
                case SOURCE_DESECRATED:
                    if (!is_suffix) {
                        extern ModifierLookup foci_desecrated_prefixes[];
                        table = foci_desecrated_prefixes;
                        count = 6;
                    }
                    else {
                        extern ModifierLookup foci_desecrated_suffixes[];
                        table = foci_desecrated_suffixes;
                        count = 11;
                    }
                    break;
                case SOURCE_ESSENCE:
                    if (!is_suffix) {
                        extern ModifierLookup foci_essence_prefixes[];
                        table = foci_essence_prefixes;
                        count = 5;
                    }
                    else {
                        extern ModifierLookup foci_essence_suffixes[];
                        table = foci_essence_suffixes;
                        count = 12;
                    }
                    break;
                default:
                    break;
            }
            break;
        case 29: // gloves_dex
            switch (source) {
                case SOURCE_NORMAL:
                    if (!is_suffix) {
                        extern ModifierLookup gloves_dex_normal_prefixes[];
                        table = gloves_dex_normal_prefixes;
                        count = 10;
                    }
                    else {
                        extern ModifierLookup gloves_dex_normal_suffixes[];
                        table = gloves_dex_normal_suffixes;
                        count = 16;
                    }
                    break;
                case SOURCE_DESECRATED:
                    if (is_suffix) {
                        extern ModifierLookup gloves_dex_desecrated_suffixes[];
                        table = gloves_dex_desecrated_suffixes;
                        count = 13;
                    }
                    break;
                case SOURCE_ESSENCE:
                    if (!is_suffix) {
                        extern ModifierLookup gloves_dex_essence_prefixes[];
                        table = gloves_dex_essence_prefixes;
                        count = 3;
                    }
                    else {
                        extern ModifierLookup gloves_dex_essence_suffixes[];
                        table = gloves_dex_essence_suffixes;
                        count = 11;
                    }
                    break;
                default:
                    break;
            }
            break;
        case 27: // gloves_dex_int
            switch (source) {
                case SOURCE_NORMAL:
                    if (!is_suffix) {
                        extern ModifierLookup gloves_dex_int_normal_prefixes[];
                        table = gloves_dex_int_normal_prefixes;
                        count = 10;
                    }
                    else {
                        extern ModifierLookup gloves_dex_int_normal_suffixes[];
                        table = gloves_dex_int_normal_suffixes;
                        count = 18;
                    }
                    break;
                case SOURCE_DESECRATED:
                    if (is_suffix) {
                        extern ModifierLookup gloves_dex_int_desecrated_suffixes[];
                        table = gloves_dex_int_desecrated_suffixes;
                        count = 16;
                    }
                    break;
                case SOURCE_ESSENCE:
                    if (!is_suffix) {
                        extern ModifierLookup gloves_dex_int_essence_prefixes[];
                        table = gloves_dex_int_essence_prefixes;
                        count = 4;
                    }
                    else {
                        extern ModifierLookup gloves_dex_int_essence_suffixes[];
                        table = gloves_dex_int_essence_suffixes;
                        count = 11;
                    }
                    break;
                default:
                    break;
            }
            break;
        case 26: // gloves_int
            switch (source) {
                case SOURCE_NORMAL:
                    if (!is_suffix) {
                        extern ModifierLookup gloves_int_normal_prefixes[];
                        table = gloves_int_normal_prefixes;
                        count = 10;
                    }
                    else {
                        extern ModifierLookup gloves_int_normal_suffixes[];
                        table = gloves_int_normal_suffixes;
                        count = 17;
                    }
                    break;
                case SOURCE_DESECRATED:
                    if (is_suffix) {
                        extern ModifierLookup gloves_int_desecrated_suffixes[];
                        table = gloves_int_desecrated_suffixes;
                        count = 15;
                    }
                    break;
                case SOURCE_ESSENCE:
                    if (!is_suffix) {
                        extern ModifierLookup gloves_int_essence_prefixes[];
                        table = gloves_int_essence_prefixes;
                        count = 4;
                    }
                    else {
                        extern ModifierLookup gloves_int_essence_suffixes[];
                        table = gloves_int_essence_suffixes;
                        count = 11;
                    }
                    break;
                default:
                    break;
            }
            break;
        case 28: // gloves_str
            switch (source) {
                case SOURCE_NORMAL:
                    if (!is_suffix) {
                        extern ModifierLookup gloves_str_normal_prefixes[];
                        table = gloves_str_normal_prefixes;
                        count = 10;
                    }
                    else {
                        extern ModifierLookup gloves_str_normal_suffixes[];
                        table = gloves_str_normal_suffixes;
                        count = 17;
                    }
                    break;
                case SOURCE_DESECRATED:
                    if (is_suffix) {
                        extern ModifierLookup gloves_str_desecrated_suffixes[];
                        table = gloves_str_desecrated_suffixes;
                        count = 12;
                    }
                    break;
                case SOURCE_ESSENCE:
                    if (!is_suffix) {
                        extern ModifierLookup gloves_str_essence_prefixes[];
                        table = gloves_str_essence_prefixes;
                        count = 4;
                    }
                    else {
                        extern ModifierLookup gloves_str_essence_suffixes[];
                        table = gloves_str_essence_suffixes;
                        count = 11;
                    }
                    break;
                default:
                    break;
            }
            break;
        case 30: // gloves_str_dex
            switch (source) {
                case SOURCE_NORMAL:
                    if (!is_suffix) {
                        extern ModifierLookup gloves_str_dex_normal_prefixes[];
                        table = gloves_str_dex_normal_prefixes;
                        count = 10;
                    }
                    else {
                        extern ModifierLookup gloves_str_dex_normal_suffixes[];
                        table = gloves_str_dex_normal_suffixes;
                        count = 19;
                    }
                    break;
                case SOURCE_DESECRATED:
                    if (is_suffix) {
                        extern ModifierLookup gloves_str_dex_desecrated_suffixes[];
                        table = gloves_str_dex_desecrated_suffixes;
                        count = 14;
                    }
                    break;
                case SOURCE_ESSENCE:
                    if (!is_suffix) {
                        extern ModifierLookup gloves_str_dex_essence_prefixes[];
                        table = gloves_str_dex_essence_prefixes;
                        count = 4;
                    }
                    else {
                        extern ModifierLookup gloves_str_dex_essence_suffixes[];
                        table = gloves_str_dex_essence_suffixes;
                        count = 11;
                    }
                    break;
                default:
                    break;
            }
            break;
        case 25: // gloves_str_int
            switch (source) {
                case SOURCE_NORMAL:
                    if (!is_suffix) {
                        extern ModifierLookup gloves_str_int_normal_prefixes[];
                        table = gloves_str_int_normal_prefixes;
                        count = 10;
                    }
                    else {
                        extern ModifierLookup gloves_str_int_normal_suffixes[];
                        table = gloves_str_int_normal_suffixes;
                        count = 18;
                    }
                    break;
                case SOURCE_DESECRATED:
                    if (is_suffix) {
                        extern ModifierLookup gloves_str_int_desecrated_suffixes[];
                        table = gloves_str_int_desecrated_suffixes;
                        count = 16;
                    }
                    break;
                case SOURCE_ESSENCE:
                    if (!is_suffix) {
                        extern ModifierLookup gloves_str_int_essence_prefixes[];
                        table = gloves_str_int_essence_prefixes;
                        count = 4;
                    }
                    else {
                        extern ModifierLookup gloves_str_int_essence_suffixes[];
                        table = gloves_str_int_essence_suffixes;
                        count = 12;
                    }
                    break;
                default:
                    break;
            }
            break;
        case 14: // helmets_dex
            switch (source) {
                case SOURCE_NORMAL:
                    if (!is_suffix) {
                        extern ModifierLookup helmets_dex_normal_prefixes[];
                        table = helmets_dex_normal_prefixes;
                        count = 8;
                    }
                    else {
                        extern ModifierLookup helmets_dex_normal_suffixes[];
                        table = helmets_dex_normal_suffixes;
                        count = 13;
                    }
                    break;
                case SOURCE_DESECRATED:
                    if (is_suffix) {
                        extern ModifierLookup helmets_dex_desecrated_suffixes[];
                        table = helmets_dex_desecrated_suffixes;
                        count = 13;
                    }
                    break;
                case SOURCE_ESSENCE:
                    if (!is_suffix) {
                        extern ModifierLookup helmets_dex_essence_prefixes[];
                        table = helmets_dex_essence_prefixes;
                        count = 3;
                    }
                    else {
                        extern ModifierLookup helmets_dex_essence_suffixes[];
                        table = helmets_dex_essence_suffixes;
                        count = 9;
                    }
                    break;
                default:
                    break;
            }
            break;
        case 12: // helmets_dex_int
            switch (source) {
                case SOURCE_NORMAL:
                    if (!is_suffix) {
                        extern ModifierLookup helmets_dex_int_normal_prefixes[];
                        table = helmets_dex_int_normal_prefixes;
                        count = 8;
                    }
                    else {
                        extern ModifierLookup helmets_dex_int_normal_suffixes[];
                        table = helmets_dex_int_normal_suffixes;
                        count = 14;
                    }
                    break;
                case SOURCE_DESECRATED:
                    if (is_suffix) {
                        extern ModifierLookup helmets_dex_int_desecrated_suffixes[];
                        table = helmets_dex_int_desecrated_suffixes;
                        count = 14;
                    }
                    break;
                case SOURCE_ESSENCE:
                    if (!is_suffix) {
                        extern ModifierLookup helmets_dex_int_essence_prefixes[];
                        table = helmets_dex_int_essence_prefixes;
                        count = 3;
                    }
                    else {
                        extern ModifierLookup helmets_dex_int_essence_suffixes[];
                        table = helmets_dex_int_essence_suffixes;
                        count = 9;
                    }
                    break;
                default:
                    break;
            }
            break;
        case 11: // helmets_int
            switch (source) {
                case SOURCE_NORMAL:
                    if (!is_suffix) {
                        extern ModifierLookup helmets_int_normal_prefixes[];
                        table = helmets_int_normal_prefixes;
                        count = 8;
                    }
                    else {
                        extern ModifierLookup helmets_int_normal_suffixes[];
                        table = helmets_int_normal_suffixes;
                        count = 12;
                    }
                    break;
                case SOURCE_DESECRATED:
                    if (is_suffix) {
                        extern ModifierLookup helmets_int_desecrated_suffixes[];
                        table = helmets_int_desecrated_suffixes;
                        count = 12;
                    }
                    break;
                case SOURCE_ESSENCE:
                    if (!is_suffix) {
                        extern ModifierLookup helmets_int_essence_prefixes[];
                        table = helmets_int_essence_prefixes;
                        count = 3;
                    }
                    else {
                        extern ModifierLookup helmets_int_essence_suffixes[];
                        table = helmets_int_essence_suffixes;
                        count = 8;
                    }
                    break;
                default:
                    break;
            }
            break;
        case 13: // helmets_str
            switch (source) {
                case SOURCE_NORMAL:
                    if (!is_suffix) {
                        extern ModifierLookup helmets_str_normal_prefixes[];
                        table = helmets_str_normal_prefixes;
                        count = 8;
                    }
                    else {
                        extern ModifierLookup helmets_str_normal_suffixes[];
                        table = helmets_str_normal_suffixes;
                        count = 13;
                    }
                    break;
                case SOURCE_DESECRATED:
                    if (is_suffix) {
                        extern ModifierLookup helmets_str_desecrated_suffixes[];
                        table = helmets_str_desecrated_suffixes;
                        count = 14;
                    }
                    break;
                case SOURCE_ESSENCE:
                    if (!is_suffix) {
                        extern ModifierLookup helmets_str_essence_prefixes[];
                        table = helmets_str_essence_prefixes;
                        count = 3;
                    }
                    else {
                        extern ModifierLookup helmets_str_essence_suffixes[];
                        table = helmets_str_essence_suffixes;
                        count = 9;
                    }
                    break;
                default:
                    break;
            }
            break;
        case 15: // helmets_str_dex
            switch (source) {
                case SOURCE_NORMAL:
                    if (!is_suffix) {
                        extern ModifierLookup helmets_str_dex_normal_prefixes[];
                        table = helmets_str_dex_normal_prefixes;
                        count = 8;
                    }
                    else {
                        extern ModifierLookup helmets_str_dex_normal_suffixes[];
                        table = helmets_str_dex_normal_suffixes;
                        count = 14;
                    }
                    break;
                case SOURCE_DESECRATED:
                    if (is_suffix) {
                        extern ModifierLookup helmets_str_dex_desecrated_suffixes[];
                        table = helmets_str_dex_desecrated_suffixes;
                        count = 16;
                    }
                    break;
                case SOURCE_ESSENCE:
                    if (!is_suffix) {
                        extern ModifierLookup helmets_str_dex_essence_prefixes[];
                        table = helmets_str_dex_essence_prefixes;
                        count = 3;
                    }
                    else {
                        extern ModifierLookup helmets_str_dex_essence_suffixes[];
                        table = helmets_str_dex_essence_suffixes;
                        count = 10;
                    }
                    break;
                default:
                    break;
            }
            break;
        case 10: // helmets_str_int
            switch (source) {
                case SOURCE_NORMAL:
                    if (!is_suffix) {
                        extern ModifierLookup helmets_str_int_normal_prefixes[];
                        table = helmets_str_int_normal_prefixes;
                        count = 8;
                    }
                    else {
                        extern ModifierLookup helmets_str_int_normal_suffixes[];
                        table = helmets_str_int_normal_suffixes;
                        count = 14;
                    }
                    break;
                case SOURCE_DESECRATED:
                    if (is_suffix) {
                        extern ModifierLookup helmets_str_int_desecrated_suffixes[];
                        table = helmets_str_int_desecrated_suffixes;
                        count = 15;
                    }
                    break;
                case SOURCE_ESSENCE:
                    if (!is_suffix) {
                        extern ModifierLookup helmets_str_int_essence_prefixes[];
                        table = helmets_str_int_essence_prefixes;
                        count = 3;
                    }
                    else {
                        extern ModifierLookup helmets_str_int_essence_suffixes[];
                        table = helmets_str_int_essence_suffixes;
                        count = 9;
                    }
                    break;
                default:
                    break;
            }
            break;
        case 3: // onehand_maces
            switch (source) {
                case SOURCE_NORMAL:
                    if (!is_suffix) {
                        extern ModifierLookup onehand_maces_normal_prefixes[];
                        table = onehand_maces_normal_prefixes;
                        count = 8;
                    }
                    else {
                        extern ModifierLookup onehand_maces_normal_suffixes[];
                        table = onehand_maces_normal_suffixes;
                        count = 14;
                    }
                    break;
                case SOURCE_DESECRATED:
                    if (!is_suffix) {
                        extern ModifierLookup onehand_maces_desecrated_prefixes[];
                        table = onehand_maces_desecrated_prefixes;
                        count = 8;
                    }
                    else {
                        extern ModifierLookup onehand_maces_desecrated_suffixes[];
                        table = onehand_maces_desecrated_suffixes;
                        count = 8;
                    }
                    break;
                case SOURCE_ESSENCE:
                    if (!is_suffix) {
                        extern ModifierLookup onehand_maces_essence_prefixes[];
                        table = onehand_maces_essence_prefixes;
                        count = 9;
                    }
                    else {
                        extern ModifierLookup onehand_maces_essence_suffixes[];
                        table = onehand_maces_essence_suffixes;
                        count = 7;
                    }
                    break;
                default:
                    break;
            }
            break;
        case 38: // quarterstaves
            switch (source) {
                case SOURCE_NORMAL:
                    if (!is_suffix) {
                        extern ModifierLookup quarterstaves_normal_prefixes[];
                        table = quarterstaves_normal_prefixes;
                        count = 8;
                    }
                    else {
                        extern ModifierLookup quarterstaves_normal_suffixes[];
                        table = quarterstaves_normal_suffixes;
                        count = 15;
                    }
                    break;
                case SOURCE_DESECRATED:
                    if (!is_suffix) {
                        extern ModifierLookup quarterstaves_desecrated_prefixes[];
                        table = quarterstaves_desecrated_prefixes;
                        count = 6;
                    }
                    else {
                        extern ModifierLookup quarterstaves_desecrated_suffixes[];
                        table = quarterstaves_desecrated_suffixes;
                        count = 6;
                    }
                    break;
                case SOURCE_ESSENCE:
                    if (!is_suffix) {
                        extern ModifierLookup quarterstaves_essence_prefixes[];
                        table = quarterstaves_essence_prefixes;
                        count = 9;
                    }
                    else {
                        extern ModifierLookup quarterstaves_essence_suffixes[];
                        table = quarterstaves_essence_suffixes;
                        count = 7;
                    }
                    break;
                default:
                    break;
            }
            break;
        case 2: // quivers
            switch (source) {
                case SOURCE_NORMAL:
                    if (!is_suffix) {
                        extern ModifierLookup quivers_normal_prefixes[];
                        table = quivers_normal_prefixes;
                        count = 7;
                    }
                    else {
                        extern ModifierLookup quivers_normal_suffixes[];
                        table = quivers_normal_suffixes;
                        count = 8;
                    }
                    break;
                case SOURCE_DESECRATED:
                    if (!is_suffix) {
                        extern ModifierLookup quivers_desecrated_prefixes[];
                        table = quivers_desecrated_prefixes;
                        count = 1;
                    }
                    else {
                        extern ModifierLookup quivers_desecrated_suffixes[];
                        table = quivers_desecrated_suffixes;
                        count = 3;
                    }
                    break;
                case SOURCE_ESSENCE:
                    if (!is_suffix) {
                        extern ModifierLookup quivers_essence_prefixes[];
                        table = quivers_essence_prefixes;
                        count = 2;
                    }
                    else {
                        extern ModifierLookup quivers_essence_suffixes[];
                        table = quivers_essence_suffixes;
                        count = 1;
                    }
                    break;
                default:
                    break;
            }
            break;
        case 24: // rings
            switch (source) {
                case SOURCE_NORMAL:
                    if (!is_suffix) {
                        extern ModifierLookup rings_normal_prefixes[];
                        table = rings_normal_prefixes;
                        count = 13;
                    }
                    else {
                        extern ModifierLookup rings_normal_suffixes[];
                        table = rings_normal_suffixes;
                        count = 18;
                    }
                    break;
                case SOURCE_DESECRATED:
                    if (!is_suffix) {
                        extern ModifierLookup rings_desecrated_prefixes[];
                        table = rings_desecrated_prefixes;
                        count = 7;
                    }
                    else {
                        extern ModifierLookup rings_desecrated_suffixes[];
                        table = rings_desecrated_suffixes;
                        count = 15;
                    }
                    break;
                case SOURCE_ESSENCE:
                    if (!is_suffix) {
                        extern ModifierLookup rings_essence_prefixes[];
                        table = rings_essence_prefixes;
                        count = 3;
                    }
                    else {
                        extern ModifierLookup rings_essence_suffixes[];
                        table = rings_essence_suffixes;
                        count = 9;
                    }
                    break;
                default:
                    break;
            }
            break;
        case 16: // sceptres
            switch (source) {
                case SOURCE_NORMAL:
                    if (!is_suffix) {
                        extern ModifierLookup sceptres_normal_prefixes[];
                        table = sceptres_normal_prefixes;
                        count = 8;
                    }
                    else {
                        extern ModifierLookup sceptres_normal_suffixes[];
                        table = sceptres_normal_suffixes;
                        count = 13;
                    }
                    break;
                case SOURCE_ESSENCE:
                    if (!is_suffix) {
                        extern ModifierLookup sceptres_essence_prefixes[];
                        table = sceptres_essence_prefixes;
                        count = 1;
                    }
                    else {
                        extern ModifierLookup sceptres_essence_suffixes[];
                        table = sceptres_essence_suffixes;
                        count = 4;
                    }
                    break;
                default:
                    break;
            }
            break;
        case 7: // shields_str
            switch (source) {
                case SOURCE_NORMAL:
                    if (!is_suffix) {
                        extern ModifierLookup shields_str_normal_prefixes[];
                        table = shields_str_normal_prefixes;
                        count = 6;
                    }
                    else {
                        extern ModifierLookup shields_str_normal_suffixes[];
                        table = shields_str_normal_suffixes;
                        count = 14;
                    }
                    break;
                case SOURCE_DESECRATED:
                    if (is_suffix) {
                        extern ModifierLookup shields_str_desecrated_suffixes[];
                        table = shields_str_desecrated_suffixes;
                        count = 19;
                    }
                    break;
                case SOURCE_ESSENCE:
                    if (!is_suffix) {
                        extern ModifierLookup shields_str_essence_prefixes[];
                        table = shields_str_essence_prefixes;
                        count = 3;
                    }
                    else {
                        extern ModifierLookup shields_str_essence_suffixes[];
                        table = shields_str_essence_suffixes;
                        count = 5;
                    }
                    break;
                default:
                    break;
            }
            break;
        case 8: // shields_str_dex
            switch (source) {
                case SOURCE_NORMAL:
                    if (!is_suffix) {
                        extern ModifierLookup shields_str_dex_normal_prefixes[];
                        table = shields_str_dex_normal_prefixes;
                        count = 6;
                    }
                    else {
                        extern ModifierLookup shields_str_dex_normal_suffixes[];
                        table = shields_str_dex_normal_suffixes;
                        count = 15;
                    }
                    break;
                case SOURCE_DESECRATED:
                    if (is_suffix) {
                        extern ModifierLookup shields_str_dex_desecrated_suffixes[];
                        table = shields_str_dex_desecrated_suffixes;
                        count = 19;
                    }
                    break;
                case SOURCE_ESSENCE:
                    if (!is_suffix) {
                        extern ModifierLookup shields_str_dex_essence_prefixes[];
                        table = shields_str_dex_essence_prefixes;
                        count = 3;
                    }
                    else {
                        extern ModifierLookup shields_str_dex_essence_suffixes[];
                        table = shields_str_dex_essence_suffixes;
                        count = 6;
                    }
                    break;
                default:
                    break;
            }
            break;
        case 6: // shields_str_int
            switch (source) {
                case SOURCE_NORMAL:
                    if (!is_suffix) {
                        extern ModifierLookup shields_str_int_normal_prefixes[];
                        table = shields_str_int_normal_prefixes;
                        count = 6;
                    }
                    else {
                        extern ModifierLookup shields_str_int_normal_suffixes[];
                        table = shields_str_int_normal_suffixes;
                        count = 16;
                    }
                    break;
                case SOURCE_DESECRATED:
                    if (is_suffix) {
                        extern ModifierLookup shields_str_int_desecrated_suffixes[];
                        table = shields_str_int_desecrated_suffixes;
                        count = 19;
                    }
                    break;
                case SOURCE_ESSENCE:
                    if (!is_suffix) {
                        extern ModifierLookup shields_str_int_essence_prefixes[];
                        table = shields_str_int_essence_prefixes;
                        count = 3;
                    }
                    else {
                        extern ModifierLookup shields_str_int_essence_suffixes[];
                        table = shields_str_int_essence_suffixes;
                        count = 6;
                    }
                    break;
                default:
                    break;
            }
            break;
        case 5: // spears
            switch (source) {
                case SOURCE_NORMAL:
                    if (!is_suffix) {
                        extern ModifierLookup spears_normal_prefixes[];
                        table = spears_normal_prefixes;
                        count = 8;
                    }
                    else {
                        extern ModifierLookup spears_normal_suffixes[];
                        table = spears_normal_suffixes;
                        count = 16;
                    }
                    break;
                case SOURCE_DESECRATED:
                    if (!is_suffix) {
                        extern ModifierLookup spears_desecrated_prefixes[];
                        table = spears_desecrated_prefixes;
                        count = 6;
                    }
                    else {
                        extern ModifierLookup spears_desecrated_suffixes[];
                        table = spears_desecrated_suffixes;
                        count = 8;
                    }
                    break;
                case SOURCE_ESSENCE:
                    if (!is_suffix) {
                        extern ModifierLookup spears_essence_prefixes[];
                        table = spears_essence_prefixes;
                        count = 9;
                    }
                    else {
                        extern ModifierLookup spears_essence_suffixes[];
                        table = spears_essence_suffixes;
                        count = 7;
                    }
                    break;
                default:
                    break;
            }
            break;
        case 40: // staves
            switch (source) {
                case SOURCE_NORMAL:
                    if (!is_suffix) {
                        extern ModifierLookup staves_normal_prefixes[];
                        table = staves_normal_prefixes;
                        count = 11;
                    }
                    else {
                        extern ModifierLookup staves_normal_suffixes[];
                        table = staves_normal_suffixes;
                        count = 18;
                    }
                    break;
                case SOURCE_DESECRATED:
                    if (!is_suffix) {
                        extern ModifierLookup staves_desecrated_prefixes[];
                        table = staves_desecrated_prefixes;
                        count = 4;
                    }
                    else {
                        extern ModifierLookup staves_desecrated_suffixes[];
                        table = staves_desecrated_suffixes;
                        count = 5;
                    }
                    break;
                case SOURCE_ESSENCE:
                    if (!is_suffix) {
                        extern ModifierLookup staves_essence_prefixes[];
                        table = staves_essence_prefixes;
                        count = 1;
                    }
                    else {
                        extern ModifierLookup staves_essence_suffixes[];
                        table = staves_essence_suffixes;
                        count = 7;
                    }
                    break;
                default:
                    break;
            }
            break;
        case 9: // twohand_maces
            switch (source) {
                case SOURCE_NORMAL:
                    if (!is_suffix) {
                        extern ModifierLookup twohand_maces_normal_prefixes[];
                        table = twohand_maces_normal_prefixes;
                        count = 8;
                    }
                    else {
                        extern ModifierLookup twohand_maces_normal_suffixes[];
                        table = twohand_maces_normal_suffixes;
                        count = 14;
                    }
                    break;
                case SOURCE_DESECRATED:
                    if (!is_suffix) {
                        extern ModifierLookup twohand_maces_desecrated_prefixes[];
                        table = twohand_maces_desecrated_prefixes;
                        count = 8;
                    }
                    else {
                        extern ModifierLookup twohand_maces_desecrated_suffixes[];
                        table = twohand_maces_desecrated_suffixes;
                        count = 8;
                    }
                    break;
                case SOURCE_ESSENCE:
                    if (!is_suffix) {
                        extern ModifierLookup twohand_maces_essence_prefixes[];
                        table = twohand_maces_essence_prefixes;
                        count = 9;
                    }
                    else {
                        extern ModifierLookup twohand_maces_essence_suffixes[];
                        table = twohand_maces_essence_suffixes;
                        count = 7;
                    }
                    break;
                default:
                    break;
            }
            break;
        case 37: // wands
            switch (source) {
                case SOURCE_NORMAL:
                    if (!is_suffix) {
                        extern ModifierLookup wands_normal_prefixes[];
                        table = wands_normal_prefixes;
                        count = 11;
                    }
                    else {
                        extern ModifierLookup wands_normal_suffixes[];
                        table = wands_normal_suffixes;
                        count = 18;
                    }
                    break;
                case SOURCE_DESECRATED:
                    if (!is_suffix) {
                        extern ModifierLookup wands_desecrated_prefixes[];
                        table = wands_desecrated_prefixes;
                        count = 5;
                    }
                    else {
                        extern ModifierLookup wands_desecrated_suffixes[];
                        table = wands_desecrated_suffixes;
                        count = 8;
                    }
                    break;
                case SOURCE_ESSENCE:
                    if (!is_suffix) {
                        extern ModifierLookup wands_essence_prefixes[];
                        table = wands_essence_prefixes;
                        count = 1;
                    }
                    else {
                        extern ModifierLookup wands_essence_suffixes[];
                        table = wands_essence_suffixes;
                        count = 7;
                    }
                    break;
                default:
                    break;
            }
            break;
        default:
            break;
    }
    
    *out_count = count;
    return table;
}
